[package]
name = "hello_bevy"
version = "0.1.0"
authors = ["Troligtvis <karljohan@codefork.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.2"
rand = "0.7.3"